version: '2.2'
services:
  server:
    image: server
    ports:
      - 8001:8000

  api:
    image: api
    ports:
      - 8000:8000

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./library.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: changeme
